version: "3.8"

services:
    laravel-app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        environment:
            - APACHE_RUN_USER=www-data
            - APACHE_RUN_GROUP=www-data
        container_name: tcg-market-app
